In [4]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sn 
import numpy as np 
from tensorflow.keras import datasets, layers , models 
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

## Load Dataset 

In [5]:
df_full_feature = pd.read_csv('../Dataset/Murni/processed_dataset_10.csv',sep=',')
df_chi_square = pd.read_csv('../Dataset/Murni/processed_dataset_chi_square.csv', sep=',')
df_feature_selection = pd.read_csv('../Dataset/Murni/processed_dataset_5.csv',sep=',')
df_slice = pd.read_csv('../Dataset/Murni/processed_dataset_slice.csv',sep=',')

## Splitting Features And Label 

In [6]:
# Dataset Full Feature
full_feature_x = df_full_feature[df_full_feature.columns[:9]]
full_feature_y = df_full_feature['label']

full_feature_x.head(5)

src   dst  Protocol  pktrate  pktperflow  dur   dur_nsec  bytecount  \
0   0.0  16.0         3      451       13535  100  716000000   48294064   
1   0.0  16.0         3      451       13531  280  734000000  134737070   
2  10.0  16.0         3      451       13534  200  744000000   96294978   
3  10.0  16.0         3      451       13534  200  744000000   96294978   
4  10.0  16.0         3      451       13534  200  744000000   96294978   

   pktcount  
0     45304  
1    126395  
2     90333  
3     90333  
4     90333

In [7]:
# Dataset Chi Square 
chi_square_x = df_chi_square[df_chi_square.columns[:5]]
chi_square_y = df_chi_square['label']

chi_square_x.head(5)

dst   src  Protocol  pktcount  pktcount.1
0  16.0   0.0         3     45304       45304
1  16.0   0.0         3    126395      126395
2  16.0  10.0         3     90333       90333
3  16.0  10.0         3     90333       90333
4  16.0  10.0         3     90333       90333

In [8]:
# Dataset Feature Selection
feature_selection_x = df_feature_selection[df_feature_selection.columns[:5]]
feature_selection_y = df_feature_selection['label']

feature_selection_x.head(5)

pktrate  pktperflow  Protocol   src   dst
0      451       13535         3   0.0  16.0
1      451       13531         3   0.0  16.0
2      451       13534         3  10.0  16.0
3      451       13534         3  10.0  16.0
4      451       13534         3  10.0  16.0

In [25]:
# Dataset Slice
slice_x = df_slice[df_slice.columns[:4]]
slice_y= df_slice['label']

slice_x.head(5)

dst   src  Protocol  bytecount
0  16.0   0.0         3   48294064
1  16.0   0.0         3  134737070
2  16.0  10.0         3   96294978
3  16.0  10.0         3   96294978
4  16.0  10.0         3   96294978

## Full Feature Model

In [31]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(full_feature_x,full_feature_y,test_size=0.30,random_state=6)

### Create Model

In [50]:
model_full = models.Sequential([
    layers.Dense(2000, input_dim=9, activation='relu'),
    layers.Dense(1000, activation='sigmoid'),
    layers.Dense(500, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_full.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_full.fit(x_train, y_train, epochs=5)

Epoch 1/5
2257/2257 [==============================] - 107s 47ms/step - loss: 0.7752 - accuracy: 0.6260
Epoch 2/5
2257/2257 [==============================] - 133s 59ms/step - loss: 0.6174 - accuracy: 0.6457
Epoch 3/5
2257/2257 [==============================] - 116s 51ms/step - loss: 0.6322 - accuracy: 0.6428
Epoch 4/5
2257/2257 [==============================] - 102s 45ms/step - loss: 0.6320 - accuracy: 0.6466
Epoch 5/5
2257/2257 [==============================] - 110s 49ms/step - loss: 0.6315 - accuracy: 0.6480


In [51]:
y_pred_train = model_full.predict(x_train)
y_pred_test = model_full.predict(x_test)

#### Training 

In [52]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[29279 14733]
 [10619 17570]]
              precision    recall  f1-score   support

           0       0.73      0.67      0.70     44012
           1       0.54      0.62      0.58     28189

    accuracy                           0.65     72201
   macro avg       0.64      0.64      0.64     72201
weighted avg       0.66      0.65      0.65     72201

Accuracy: 64.88691292364372


#### Testing

In [47]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[16808  1975]
 [ 8988  3173]]
              precision    recall  f1-score   support

           0       0.65      0.89      0.75     18783
           1       0.62      0.26      0.37     12161

    accuracy                           0.65     30944
   macro avg       0.63      0.58      0.56     30944
weighted avg       0.64      0.65      0.60     30944

Accuracy: 64.57148397104446


### Chi Square Model

In [53]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(chi_square_x,chi_square_y,test_size=0.30,random_state=5)

In [58]:
model_chi = models.Sequential([
    layers.Dense(2000, input_dim=5, activation='relu'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(500, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_chi.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_chi.fit(x_train, y_train, epochs=5)

Epoch 1/5
2257/2257 [==============================] - 32s 14ms/step - loss: 0.6934 - accuracy: 0.5906
Epoch 2/5
2257/2257 [==============================] - 30s 13ms/step - loss: 0.6697 - accuracy: 0.6101
Epoch 3/5
2257/2257 [==============================] - 28s 12ms/step - loss: 0.6705 - accuracy: 0.60770s - loss: 0.6706 - 
Epoch 4/5
2257/2257 [==============================] - 26s 12ms/step - loss: 0.6696 - accuracy: 0.6088
Epoch 5/5
2257/2257 [==============================] - 25s 11ms/step - loss: 0.6707 - accuracy: 0.6061


In [59]:
y_pred_train = model_chi.predict(x_train)
y_pred_test = model_chi.predict(x_test)

#### Training 

In [60]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[44012     0]
 [28140    49]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76     44012
           1       1.00      0.00      0.00     28189

    accuracy                           0.61     72201
   macro avg       0.80      0.50      0.38     72201
weighted avg       0.76      0.61      0.46     72201

Accuracy: 61.02547056134957


#### Testing

In [61]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[18783     0]
 [12136    25]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76     18783
           1       1.00      0.00      0.00     12161

    accuracy                           0.61     30944
   macro avg       0.80      0.50      0.38     30944
weighted avg       0.76      0.61      0.46     30944

Accuracy: 60.78076525336091


### Feature Selection Model 

In [62]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(feature_selection_x,feature_selection_y,test_size=0.30,random_state=5)

In [63]:
model_feature_selection = models.Sequential([
    layers.Dense(2000, input_dim=5, activation='relu'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(500, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_feature_selection.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_feature_selection.fit(x_train, y_train, epochs=10)

Epoch 1/5
2257/2257 [==============================] - 20s 9ms/step - loss: 0.5804 - accuracy: 0.6435
Epoch 2/5
2257/2257 [==============================] - 22s 10ms/step - loss: 0.5380 - accuracy: 0.6607
Epoch 3/5
2257/2257 [==============================] - 21s 9ms/step - loss: 0.5383 - accuracy: 0.6665
Epoch 4/5
2257/2257 [==============================] - 21s 9ms/step - loss: 0.5354 - accuracy: 0.6740
Epoch 5/5
2257/2257 [==============================] - 21s 9ms/step - loss: 0.5359 - accuracy: 0.6700


In [64]:
y_pred_train = model_feature_selection.predict(x_train)
y_pred_test = model_feature_selection.predict(x_test)

#### Training  

In [65]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[22051 22000]
 [ 1874 26276]]
              precision    recall  f1-score   support

           0       0.92      0.50      0.65     44051
           1       0.54      0.93      0.69     28150

    accuracy                           0.67     72201
   macro avg       0.73      0.72      0.67     72201
weighted avg       0.77      0.67      0.66     72201

Accuracy: 66.93397598371213


#### Training 

In [66]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[ 9356  9388]
 [  789 11411]]
              precision    recall  f1-score   support

           0       0.92      0.50      0.65     18744
           1       0.55      0.94      0.69     12200

    accuracy                           0.67     30944
   macro avg       0.74      0.72      0.67     30944
weighted avg       0.77      0.67      0.67     30944

Accuracy: 67.1115563598759


### Slice Model

In [67]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(slice_x,slice_y,test_size=0.30,random_state=5)

In [69]:
model_slice = models.Sequential([
    layers.Dense(2000, input_dim=4, activation='relu'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(500, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_slice.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_slice.fit(x_train, y_train, epochs=5)

Epoch 1/5
2257/2257 [==============================] - 19s 8ms/step - loss: 0.7010 - accuracy: 0.5930
Epoch 2/5
2257/2257 [==============================] - 21s 10ms/step - loss: 0.6692 - accuracy: 0.6113
Epoch 3/5
2257/2257 [==============================] - 21s 9ms/step - loss: 0.6686 - accuracy: 0.6112
Epoch 4/5
2257/2257 [==============================] - 21s 9ms/step - loss: 0.6686 - accuracy: 0.6108
Epoch 5/5
2257/2257 [==============================] - 22s 10ms/step - loss: 0.6668 - accuracy: 0.6141


In [70]:
y_pred_train = model_slice.predict(x_train)
y_pred_test = model_slice.predict(x_test)

In [71]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[44037    14]
 [28107    43]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76     44051
           1       0.75      0.00      0.00     28150

    accuracy                           0.61     72201
   macro avg       0.68      0.50      0.38     72201
weighted avg       0.67      0.61      0.46     72201

Accuracy: 61.051785986343674


In [72]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[18740     4]
 [12189    11]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.75     18744
           1       0.73      0.00      0.00     12200

    accuracy                           0.61     30944
   macro avg       0.67      0.50      0.38     30944
weighted avg       0.66      0.61      0.46     30944

Accuracy: 60.59656153050672
