In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sn 
import numpy as np 
from tensorflow.keras import datasets, layers , models 
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

### Loading Dataset 

In [2]:
df_full_feature = pd.read_csv('../Dataset/Normalisasi/processed_dataset_10_norm.csv',sep=',')
df_chi_square = pd.read_csv('../Dataset/Normalisasi/processed_dataset_chi_square_norm.csv', sep=',')
df_feature_selection = pd.read_csv('../Dataset/Normalisasi/processed_dataset_5_norm.csv',sep=',')
df_slice = pd.read_csv('../Dataset/Normalisasi/processed_dataset_slice_norm.csv',sep=',')

### Splitting Variable 

In [3]:
# Dataset Full Feature
full_feature_x = df_full_feature[df_full_feature.columns[:9]]
full_feature_y = df_full_feature['label']

full_feature_x.head(5)

src       dst  Protocol   pktrate  pktperflow       dur  dur_nsec  \
0  0.055556  0.647059       0.0  0.000000    0.001511  0.522594  0.235235   
1  0.333333  0.705882       0.5  0.799687    0.799583  0.204147  0.114114   
2  0.555556  0.882353       0.0  0.001565    0.001563  0.436470  0.243243   
3  0.833333  0.941176       0.5  0.516432    0.516884  0.052100  0.622623   
4  0.111111  0.647059       1.0  0.428795    0.428504  0.152578  0.579580   

   bytecount  pktcount  
0   0.000640  0.003696  
1   0.081254  0.851453  
2   0.000534  0.003081  
3   0.014585  0.125043  
4   0.618070  0.335646

In [4]:
# Dataset Chi Square 
chi_square_x = df_chi_square[df_chi_square.columns[:5]]
chi_square_y = df_chi_square['label']

chi_square_x.head(5)

dst       src  Protocol  pktcount  pktcount.1
0  0.647059  0.055556       0.0  0.003696    0.003696
1  0.705882  0.333333       0.5  0.851453    0.851453
2  0.882353  0.555556       0.0  0.003081    0.003081
3  0.941176  0.833333       0.5  0.125043    0.125043
4  0.647059  0.111111       1.0  0.335646    0.335646

In [5]:
# Dataset Feature Selection
feature_selection_x = df_feature_selection[df_feature_selection.columns[:5]]
feature_selection_y = df_feature_selection['label']

feature_selection_x.head(5)

pktrate  pktperflow  Protocol       src       dst
0  0.000000    0.001511       0.0  0.055556  0.647059
1  0.799687    0.799583       0.5  0.333333  0.705882
2  0.001565    0.001563       0.0  0.555556  0.882353
3  0.516432    0.516884       0.5  0.833333  0.941176
4  0.428795    0.428504       1.0  0.111111  0.647059

In [6]:
# Dataset Slice
slice_x = df_slice[df_slice.columns[:4]]
slice_y= df_slice['label']

slice_x.head(5)

dst       src  Protocol  bytecount
0  0.647059  0.055556       0.0   0.000640
1  0.705882  0.333333       0.5   0.081254
2  0.882353  0.555556       0.0   0.000534
3  0.941176  0.833333       0.5   0.014585
4  0.647059  0.111111       1.0   0.618070

### Full Model

In [7]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(full_feature_x,full_feature_y,test_size=0.30,random_state=9)

In [8]:
model_full = models.Sequential([
    layers.Dense(2000, input_dim=9, activation='sigmoid'),
    layers.Dense(1000, activation='sigmoid'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(2, activation='softmax')
])
model_full.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_full.fit(x_train, y_train, epochs=10)

Epoch 1/10
1580/1580 [==============================] - 37s 23ms/step - loss: 0.6143 - accuracy: 0.64530s - loss: 0.6147 - accuracy: 
Epoch 2/10
1580/1580 [==============================] - 41s 26ms/step - loss: 0.3019 - accuracy: 0.8736
Epoch 3/10
1580/1580 [==============================] - 36s 23ms/step - loss: 0.2306 - accuracy: 0.8741
Epoch 4/10
1580/1580 [==============================] - 34s 22ms/step - loss: 0.2142 - accuracy: 0.8791
Epoch 5/10
1580/1580 [==============================] - ETA: 0s - loss: 0.2007 - accuracy: 0.88 - 34s 22ms/step - loss: 0.2007 - accuracy: 0.8872
Epoch 6/10
1580/1580 [==============================] - 34s 21ms/step - loss: 0.1840 - accuracy: 0.9044
Epoch 7/10
1580/1580 [==============================] - 34s 22ms/step - loss: 0.1782 - accuracy: 0.91161s - loss: 0.1783 - accuracy
Epoch 8/10
1580/1580 [==============================] - 35s 22ms/step - loss: 0.1729 - accuracy: 0.9165
Epoch 9/10
1580/1580 [==============================] - 34s 22ms/ste

In [9]:
y_pred_train = model_full.predict(x_train)
y_pred_test = model_full.predict(x_test)

#### Training 

In [10]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[28159  2630]
 [  622 19129]]
              precision    recall  f1-score   support

           0       0.98      0.91      0.95     30789
           1       0.88      0.97      0.92     19751

    accuracy                           0.94     50540
   macro avg       0.93      0.94      0.93     50540
weighted avg       0.94      0.94      0.94     50540

Accuracy: 93.56549267906608


#### Testing 

In [11]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[12095  1135]
 [  266  8165]]
              precision    recall  f1-score   support

           0       0.98      0.91      0.95     13230
           1       0.88      0.97      0.92      8431

    accuracy                           0.94     21661
   macro avg       0.93      0.94      0.93     21661
weighted avg       0.94      0.94      0.94     21661

Accuracy: 93.53215456350122


### Chi Model 

In [12]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(chi_square_x,chi_square_y,test_size=0.30,random_state=10)

In [14]:
model_chi = models.Sequential([
    layers.Dense(2000, input_dim=5, activation='sigmoid'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(2, activation='softmax')
])
model_chi.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_chi.fit(x_train, y_train, epochs=10)

Epoch 1/10
1580/1580 [==============================] - 21s 13ms/step - loss: 0.6356 - accuracy: 0.6132
Epoch 2/10
1580/1580 [==============================] - 23s 14ms/step - loss: 0.5056 - accuracy: 0.6677
Epoch 3/10
1580/1580 [==============================] - 21s 13ms/step - loss: 0.4963 - accuracy: 0.6682
Epoch 4/10
1580/1580 [==============================] - 20s 12ms/step - loss: 0.4937 - accuracy: 0.6739
Epoch 5/10
1580/1580 [==============================] - 21s 13ms/step - loss: 0.4914 - accuracy: 0.67820s - los
Epoch 6/10
1580/1580 [==============================] - 19s 12ms/step - loss: 0.4844 - accuracy: 0.6855
Epoch 7/10
1580/1580 [==============================] - 19s 12ms/step - loss: 0.4731 - accuracy: 0.7007
Epoch 8/10
1580/1580 [==============================] - 19s 12ms/step - loss: 0.4509 - accuracy: 0.7189
Epoch 9/10
1580/1580 [==============================] - 18s 12ms/step - loss: 0.4224 - accuracy: 0.72671s - l - ETA: 0s - loss: 0.4224 - accura
Epoch 10/10
1580

In [ ]:
y_pred_train = model_chi.predict(x_train)
y_pred_test = model_chi.predict(x_test)

#### Training 

In [ ]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[40255  3640]
 [  872 27434]]
              precision    recall  f1-score   support

           0       0.98      0.92      0.95     43895
           1       0.88      0.97      0.92     28306

    accuracy                           0.94     72201
   macro avg       0.93      0.94      0.94     72201
weighted avg       0.94      0.94      0.94     72201

Accuracy: 93.75077907508206


#### Testing 

In [ ]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[17286  1614]
 [  369 11675]]
              precision    recall  f1-score   support

           0       0.98      0.91      0.95     18900
           1       0.88      0.97      0.92     12044

    accuracy                           0.94     30944
   macro avg       0.93      0.94      0.93     30944
weighted avg       0.94      0.94      0.94     30944

Accuracy: 93.5916494312306


### Feature Selection Model 

In [ ]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(feature_selection_x,feature_selection_y,test_size=0.30,random_state=5)

In [ ]:
model_feature_selection = models.Sequential([
    layers.Dense(2000, input_dim=5, activation='relu'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(500, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_feature_selection.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_feature_selection.fit(x_train, y_train, epochs=10)

Epoch 1/10
2257/2257 [==============================] - 25s 11ms/step - loss: 0.3661 - accuracy: 0.8359
Epoch 2/10
2257/2257 [==============================] - 25s 11ms/step - loss: 0.2414 - accuracy: 0.9028
Epoch 3/10
2257/2257 [==============================] - 27s 12ms/step - loss: 0.2300 - accuracy: 0.9069
Epoch 4/10
2257/2257 [==============================] - 28s 12ms/step - loss: 0.2235 - accuracy: 0.9091
Epoch 5/10
2257/2257 [==============================] - 32s 14ms/step - loss: 0.2126 - accuracy: 0.9159
Epoch 6/10
2257/2257 [==============================] - 32s 14ms/step - loss: 0.2049 - accuracy: 0.9231
Epoch 7/10
2257/2257 [==============================] - 28s 13ms/step - loss: 0.1934 - accuracy: 0.93000s - - ETA: 0s - loss: 0.1934 - accuracy: 
Epoch 8/10
2257/2257 [==============================] - 31s 14ms/step - loss: 0.1815 - accuracy: 0.9339
Epoch 9/10
2257/2257 [==============================] - 27s 12ms/step - loss: 0.1834 - accuracy: 0.9331
Epoch 10/10
2257/2257 

In [ ]:
y_pred_train = model_feature_selection.predict(x_train)
y_pred_test = model_feature_selection.predict(x_test)

#### Training

In [ ]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[42358  1693]
 [ 2517 25633]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95     44051
           1       0.94      0.91      0.92     28150

    accuracy                           0.94     72201
   macro avg       0.94      0.94      0.94     72201
weighted avg       0.94      0.94      0.94     72201

Accuracy: 94.16905583025166


#### Testing 

In [ ]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[18046   698]
 [ 1062 11138]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95     18744
           1       0.94      0.91      0.93     12200

    accuracy                           0.94     30944
   macro avg       0.94      0.94      0.94     30944
weighted avg       0.94      0.94      0.94     30944

Accuracy: 94.31230610134436


### Slice Model 

In [ ]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(slice_x,slice_y,test_size=0.20,random_state=4)

In [ ]:
model_slice = models.Sequential([
    layers.Dense(2000, input_dim=4, activation='relu'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(50, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_slice.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_slice.fit(x_train, y_train, epochs=20)

Epoch 1/20
2579/2579 [==============================] - 21s 8ms/step - loss: 0.4456 - accuracy: 0.7245
Epoch 2/20
2579/2579 [==============================] - 23s 9ms/step - loss: 0.3702 - accuracy: 0.7846
Epoch 3/20
2579/2579 [==============================] - 22s 9ms/step - loss: 0.3488 - accuracy: 0.8004
Epoch 4/20
2579/2579 [==============================] - 23s 9ms/step - loss: 0.3366 - accuracy: 0.8034
Epoch 5/20
2579/2579 [==============================] - 23s 9ms/step - loss: 0.3144 - accuracy: 0.8181
Epoch 6/20
2579/2579 [==============================] - 23s 9ms/step - loss: 0.3021 - accuracy: 0.8275
Epoch 7/20
2579/2579 [==============================] - 24s 9ms/step - loss: 0.2857 - accuracy: 0.8353
Epoch 8/20
2579/2579 [==============================] - 24s 9ms/step - loss: 0.2802 - accuracy: 0.8364
Epoch 9/20
2579/2579 [==============================] - 25s 10ms/step - loss: 0.2703 - accuracy: 0.8402
Epoch 10/20
2579/2579 [==============================] - 25s 10ms/step -

In [ ]:
y_pred_train = model_slice.predict(x_train)
y_pred_test = model_slice.predict(x_test)

#### Training 

In [ ]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[38366  5685]
 [ 3022 25128]]
              precision    recall  f1-score   support

           0       0.93      0.87      0.90     44051
           1       0.82      0.89      0.85     28150

    accuracy                           0.88     72201
   macro avg       0.87      0.88      0.88     72201
weighted avg       0.88      0.88      0.88     72201

Accuracy: 87.94061024085539


#### Testing 

In [ ]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[15643  3101]
 [  809 11391]]
              precision    recall  f1-score   support

           0       0.95      0.83      0.89     18744
           1       0.79      0.93      0.85     12200

    accuracy                           0.87     30944
   macro avg       0.87      0.88      0.87     30944
weighted avg       0.89      0.87      0.87     30944

Accuracy: 87.36427094105481
