In [4]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sn 
import numpy as np 
from tensorflow.keras import datasets, layers , models 
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

### Loading Dataset 

In [5]:
df_full_feature = pd.read_csv('../Dataset/Normalisasi/processed_dataset_10_norm.csv',sep=',')
df_chi_square = pd.read_csv('../Dataset/Normalisasi/processed_dataset_chi_square_norm.csv', sep=',')
df_feature_selection = pd.read_csv('../Dataset/Normalisasi/processed_dataset_5_norm.csv',sep=',')
df_slice = pd.read_csv('../Dataset/Normalisasi/processed_dataset_slice_norm.csv',sep=',')

### Splitting Variable 

In [6]:
# Dataset Full Feature
full_feature_x = df_full_feature[df_full_feature.columns[:9]]
full_feature_y = df_full_feature['label']

full_feature_x.head(5)

src       dst  Protocol  pktrate  pktperflow       dur  dur_nsec  \
0  0.000000  0.941176       1.0  0.70579    0.705315  0.053163  0.716717   
1  0.000000  0.941176       1.0  0.70579    0.705107  0.148857  0.734735   
2  0.555556  0.941176       1.0  0.70579    0.705263  0.106326  0.744745   
3  0.555556  0.941176       1.0  0.70579    0.705263  0.106326  0.744745   
4  0.555556  0.941176       1.0  0.70579    0.705263  0.106326  0.744745   

   bytecount  pktcount  
0   0.328245  0.174242  
1   0.915781  0.486123  
2   0.654498  0.347427  
3   0.654498  0.347427  
4   0.654498  0.347427

In [7]:
# Dataset Chi Square 
chi_square_x = df_chi_square[df_chi_square.columns[:5]]
chi_square_y = df_chi_square['label']

chi_square_x.head(5)

dst       src  Protocol  pktcount  pktcount.1
0  0.941176  0.000000       1.0  0.174242    0.174242
1  0.941176  0.000000       1.0  0.486123    0.486123
2  0.941176  0.555556       1.0  0.347427    0.347427
3  0.941176  0.555556       1.0  0.347427    0.347427
4  0.941176  0.555556       1.0  0.347427    0.347427

In [8]:
# Dataset Feature Selection
feature_selection_x = df_feature_selection[df_feature_selection.columns[:5]]
feature_selection_y = df_feature_selection['label']

feature_selection_x.head(5)

pktrate  pktperflow  Protocol       src       dst
0  0.70579    0.705315       1.0  0.000000  0.941176
1  0.70579    0.705107       1.0  0.000000  0.941176
2  0.70579    0.705263       1.0  0.555556  0.941176
3  0.70579    0.705263       1.0  0.555556  0.941176
4  0.70579    0.705263       1.0  0.555556  0.941176

In [9]:
# Dataset Slice
slice_x = df_slice[df_slice.columns[:4]]
slice_y= df_slice['label']

slice_x.head(5)

dst       src  Protocol  bytecount
0  0.941176  0.000000       1.0   0.328245
1  0.941176  0.000000       1.0   0.915781
2  0.941176  0.555556       1.0   0.654498
3  0.941176  0.555556       1.0   0.654498
4  0.941176  0.555556       1.0   0.654498

### Full Model

In [10]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(full_feature_x,full_feature_y,test_size=0.30,random_state=9)

In [11]:
model_full = models.Sequential([
    layers.Dense(2000, input_dim=9, activation='sigmoid'),
    layers.Dense(1000, activation='sigmoid'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(2, activation='softmax')
])
model_full.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_full.fit(x_train, y_train, epochs=10)

Epoch 1/10
2257/2257 [==============================] - 43s 19ms/step - loss: 0.5795 - accuracy: 0.67750s - loss: 0.581
Epoch 2/10
2257/2257 [==============================] - 46s 20ms/step - loss: 0.2150 - accuracy: 0.9110
Epoch 3/10
2257/2257 [==============================] - 45s 20ms/step - loss: 0.1796 - accuracy: 0.9209
Epoch 4/10
2257/2257 [==============================] - 53s 24ms/step - loss: 0.1696 - accuracy: 0.9248
Epoch 5/10
2257/2257 [==============================] - 47s 21ms/step - loss: 0.1697 - accuracy: 0.9237
Epoch 6/10
2257/2257 [==============================] - 49s 21ms/step - loss: 0.1590 - accuracy: 0.9288
Epoch 7/10
2257/2257 [==============================] - 50s 22ms/step - loss: 0.1606 - accuracy: 0.9271
Epoch 8/10
2257/2257 [==============================] - 68s 30ms/step - loss: 0.1579 - accuracy: 0.9268
Epoch 9/10
2257/2257 [==============================] - 66s 29ms/step - loss: 0.1576 - accuracy: 0.9279
Epoch 10/10
2257/2257 [=========================

In [12]:
y_pred_train = model_full.predict(x_train)
y_pred_test = model_full.predict(x_test)

#### Training 

In [13]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[39872  4023]
 [  767 27539]]
              precision    recall  f1-score   support

           0       0.98      0.91      0.94     43895
           1       0.87      0.97      0.92     28306

    accuracy                           0.93     72201
   macro avg       0.93      0.94      0.93     72201
weighted avg       0.94      0.93      0.93     72201

Accuracy: 93.36574285674713


#### Testing 

In [14]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[17138  1762]
 [  343 11701]]
              precision    recall  f1-score   support

           0       0.98      0.91      0.94     18900
           1       0.87      0.97      0.92     12044

    accuracy                           0.93     30944
   macro avg       0.92      0.94      0.93     30944
weighted avg       0.94      0.93      0.93     30944

Accuracy: 93.19738883143744


### Chi Model 

In [15]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(full_feature_x,full_feature_y,test_size=0.30,random_state=9)

In [19]:
model_chi = models.Sequential([
    layers.Dense(2000, input_dim=9, activation='sigmoid'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(2, activation='softmax')
])
model_chi.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_chi.fit(x_train, y_train, epochs=10)

Epoch 1/10
2257/2257 [==============================] - 27s 12ms/step - loss: 0.5442 - accuracy: 0.6783
Epoch 2/10
2257/2257 [==============================] - 26s 11ms/step - loss: 0.2301 - accuracy: 0.8865
Epoch 3/10
2257/2257 [==============================] - 26s 11ms/step - loss: 0.1886 - accuracy: 0.9100
Epoch 4/10
2257/2257 [==============================] - 25s 11ms/step - loss: 0.1768 - accuracy: 0.9190
Epoch 5/10
2257/2257 [==============================] - 26s 11ms/step - loss: 0.1667 - accuracy: 0.9246
Epoch 6/10
2257/2257 [==============================] - 27s 12ms/step - loss: 0.1582 - accuracy: 0.9278
Epoch 7/10
2257/2257 [==============================] - 29s 13ms/step - loss: 0.1534 - accuracy: 0.9304
Epoch 8/10
2257/2257 [==============================] - 31s 14ms/step - loss: 0.1503 - accuracy: 0.93150s - loss: 0.1
Epoch 9/10
2257/2257 [==============================] - 34s 15ms/step - loss: 0.1500 - accuracy: 0.9310
Epoch 10/10
2257/2257 [===========================

In [21]:
y_pred_train = model_chi.predict(x_train)
y_pred_test = model_chi.predict(x_test)

#### Training 

In [23]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[40255  3640]
 [  872 27434]]
              precision    recall  f1-score   support

           0       0.98      0.92      0.95     43895
           1       0.88      0.97      0.92     28306

    accuracy                           0.94     72201
   macro avg       0.93      0.94      0.94     72201
weighted avg       0.94      0.94      0.94     72201

Accuracy: 93.75077907508206


#### Testing 

In [22]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[17286  1614]
 [  369 11675]]
              precision    recall  f1-score   support

           0       0.98      0.91      0.95     18900
           1       0.88      0.97      0.92     12044

    accuracy                           0.94     30944
   macro avg       0.93      0.94      0.93     30944
weighted avg       0.94      0.94      0.94     30944

Accuracy: 93.5916494312306


### Feature Selection Model 

In [24]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(feature_selection_x,feature_selection_y,test_size=0.30,random_state=5)

In [25]:
model_feature_selection = models.Sequential([
    layers.Dense(2000, input_dim=5, activation='relu'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(500, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_feature_selection.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_feature_selection.fit(x_train, y_train, epochs=10)

Epoch 1/10
2257/2257 [==============================] - 25s 11ms/step - loss: 0.3661 - accuracy: 0.8359
Epoch 2/10
2257/2257 [==============================] - 25s 11ms/step - loss: 0.2414 - accuracy: 0.9028
Epoch 3/10
2257/2257 [==============================] - 27s 12ms/step - loss: 0.2300 - accuracy: 0.9069
Epoch 4/10
2257/2257 [==============================] - 28s 12ms/step - loss: 0.2235 - accuracy: 0.9091
Epoch 5/10
2257/2257 [==============================] - 32s 14ms/step - loss: 0.2126 - accuracy: 0.9159
Epoch 6/10
2257/2257 [==============================] - 32s 14ms/step - loss: 0.2049 - accuracy: 0.9231
Epoch 7/10
2257/2257 [==============================] - 28s 13ms/step - loss: 0.1934 - accuracy: 0.93000s - - ETA: 0s - loss: 0.1934 - accuracy: 
Epoch 8/10
2257/2257 [==============================] - 31s 14ms/step - loss: 0.1815 - accuracy: 0.9339
Epoch 9/10
2257/2257 [==============================] - 27s 12ms/step - loss: 0.1834 - accuracy: 0.9331
Epoch 10/10
2257/2257 

In [26]:
y_pred_train = model_feature_selection.predict(x_train)
y_pred_test = model_feature_selection.predict(x_test)

#### Training

In [27]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[42358  1693]
 [ 2517 25633]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95     44051
           1       0.94      0.91      0.92     28150

    accuracy                           0.94     72201
   macro avg       0.94      0.94      0.94     72201
weighted avg       0.94      0.94      0.94     72201

Accuracy: 94.16905583025166


#### Testing 

In [28]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[18046   698]
 [ 1062 11138]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95     18744
           1       0.94      0.91      0.93     12200

    accuracy                           0.94     30944
   macro avg       0.94      0.94      0.94     30944
weighted avg       0.94      0.94      0.94     30944

Accuracy: 94.31230610134436


### Slice Model 

In [41]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(slice_x,slice_y,test_size=0.20,random_state=4)

In [42]:
model_slice = models.Sequential([
    layers.Dense(2000, input_dim=4, activation='relu'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(50, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_slice.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_slice.fit(x_train, y_train, epochs=20)

Epoch 1/20
2579/2579 [==============================] - 21s 8ms/step - loss: 0.4456 - accuracy: 0.7245
Epoch 2/20
2579/2579 [==============================] - 23s 9ms/step - loss: 0.3702 - accuracy: 0.7846
Epoch 3/20
2579/2579 [==============================] - 22s 9ms/step - loss: 0.3488 - accuracy: 0.8004
Epoch 4/20
2579/2579 [==============================] - 23s 9ms/step - loss: 0.3366 - accuracy: 0.8034
Epoch 5/20
2579/2579 [==============================] - 23s 9ms/step - loss: 0.3144 - accuracy: 0.8181
Epoch 6/20
2579/2579 [==============================] - 23s 9ms/step - loss: 0.3021 - accuracy: 0.8275
Epoch 7/20
2579/2579 [==============================] - 24s 9ms/step - loss: 0.2857 - accuracy: 0.8353
Epoch 8/20
2579/2579 [==============================] - 24s 9ms/step - loss: 0.2802 - accuracy: 0.8364
Epoch 9/20
2579/2579 [==============================] - 25s 10ms/step - loss: 0.2703 - accuracy: 0.8402
Epoch 10/20
2579/2579 [==============================] - 25s 10ms/step -

In [38]:
y_pred_train = model_slice.predict(x_train)
y_pred_test = model_slice.predict(x_test)

#### Training 

In [39]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[38366  5685]
 [ 3022 25128]]
              precision    recall  f1-score   support

           0       0.93      0.87      0.90     44051
           1       0.82      0.89      0.85     28150

    accuracy                           0.88     72201
   macro avg       0.87      0.88      0.88     72201
weighted avg       0.88      0.88      0.88     72201

Accuracy: 87.94061024085539


#### Testing 

In [35]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[15643  3101]
 [  809 11391]]
              precision    recall  f1-score   support

           0       0.95      0.83      0.89     18744
           1       0.79      0.93      0.85     12200

    accuracy                           0.87     30944
   macro avg       0.87      0.88      0.87     30944
weighted avg       0.89      0.87      0.87     30944

Accuracy: 87.36427094105481
