In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sn 
import numpy as np 
from tensorflow.keras import datasets, layers , models 
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

### Loading Dataset 

In [2]:
df_full_feature = pd.read_csv('../Dataset/Normalisasi/processed_dataset_10_norm.csv',sep=',')
df_chi_square = pd.read_csv('../Dataset/Normalisasi/processed_dataset_chi_square_norm.csv', sep=',')
df_feature_selection = pd.read_csv('../Dataset/Normalisasi/processed_dataset_5_norm.csv',sep=',')
df_slice = pd.read_csv('../Dataset/Normalisasi/processed_dataset_slice_norm.csv',sep=',')

### Splitting Variable 

In [3]:
# Dataset Full Feature
full_feature_x = df_full_feature[df_full_feature.columns[:9]]
full_feature_y = df_full_feature['label']

full_feature_x.head(5)

src       dst  Protocol   pktrate  pktperflow       dur  dur_nsec  \
0  0.055556  0.647059       0.0  0.000000    0.001511  0.522594  0.235235   
1  0.333333  0.705882       0.5  0.799687    0.799583  0.204147  0.114114   
2  0.555556  0.882353       0.0  0.001565    0.001563  0.436470  0.243243   
3  0.833333  0.941176       0.5  0.516432    0.516884  0.052100  0.622623   
4  0.111111  0.647059       1.0  0.428795    0.428504  0.152578  0.579580   

   bytecount  pktcount  
0   0.000640  0.003696  
1   0.081254  0.851453  
2   0.000534  0.003081  
3   0.014585  0.125043  
4   0.618070  0.335646

In [4]:
# Dataset Chi Square 
chi_square_x = df_chi_square[df_chi_square.columns[:5]]
chi_square_y = df_chi_square['label']

chi_square_x.head(5)

dst       src  Protocol  pktcount  pktcount.1
0  0.647059  0.055556       0.0  0.003696    0.003696
1  0.705882  0.333333       0.5  0.851453    0.851453
2  0.882353  0.555556       0.0  0.003081    0.003081
3  0.941176  0.833333       0.5  0.125043    0.125043
4  0.647059  0.111111       1.0  0.335646    0.335646

In [5]:
# Dataset Feature Selection
feature_selection_x = df_feature_selection[df_feature_selection.columns[:5]]
feature_selection_y = df_feature_selection['label']

feature_selection_x.head(5)

pktrate  pktperflow  Protocol       src       dst
0  0.000000    0.001511       0.0  0.055556  0.647059
1  0.799687    0.799583       0.5  0.333333  0.705882
2  0.001565    0.001563       0.0  0.555556  0.882353
3  0.516432    0.516884       0.5  0.833333  0.941176
4  0.428795    0.428504       1.0  0.111111  0.647059

In [6]:
# Dataset Slice
slice_x = df_slice[df_slice.columns[:4]]
slice_y= df_slice['label']

slice_x.head(5)

dst       src  Protocol  bytecount
0  0.647059  0.055556       0.0   0.000640
1  0.705882  0.333333       0.5   0.081254
2  0.882353  0.555556       0.0   0.000534
3  0.941176  0.833333       0.5   0.014585
4  0.647059  0.111111       1.0   0.618070

### Full Model

In [7]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(full_feature_x,full_feature_y,test_size=0.30,random_state=9)

In [8]:
model_full = models.Sequential([
    layers.Dense(2000, input_dim=9, activation='sigmoid'),
    layers.Dense(1000, activation='sigmoid'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(2, activation='softmax')
])
model_full.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_full.fit(x_train, y_train, epochs=10)

Epoch 1/10
1580/1580 [==============================] - 33s 20ms/step - loss: 0.6173 - accuracy: 0.65450s - loss: 0.6179 - accuracy: 
Epoch 2/10
1580/1580 [==============================] - 32s 21ms/step - loss: 0.2704 - accuracy: 0.8765
Epoch 3/10
1580/1580 [==============================] - ETA: 0s - loss: 0.2172 - accuracy: 0.8864 E - 33s 21ms/step - loss: 0.2172 - accuracy: 0.8864
Epoch 4/10
1580/1580 [==============================] - 33s 21ms/step - loss: 0.1913 - accuracy: 0.8997
Epoch 5/10
1580/1580 [==============================] - 32s 20ms/step - loss: 0.1752 - accuracy: 0.9175
Epoch 6/10
1580/1580 [==============================] - 33s 21ms/step - loss: 0.1658 - accuracy: 0.9238
Epoch 7/10
1580/1580 [==============================] - 33s 21ms/step - loss: 0.1618 - accuracy: 0.9270
Epoch 8/10
1580/1580 [==============================] - 33s 21ms/step - loss: 0.1610 - accuracy: 0.9265
Epoch 9/10
1580/1580 [==============================] - 34s 21ms/step - loss: 0.1530 - accur

In [9]:
y_pred_train = model_full.predict(x_train)
y_pred_test = model_full.predict(x_test)

#### Training 

In [10]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[28957  1832]
 [ 1727 18024]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     30789
           1       0.91      0.91      0.91     19751

    accuracy                           0.93     50540
   macro avg       0.93      0.93      0.93     50540
weighted avg       0.93      0.93      0.93     50540

Accuracy: 92.95805302730511


#### Testing 

In [11]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[12433   797]
 [  751  7680]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     13230
           1       0.91      0.91      0.91      8431

    accuracy                           0.93     21661
   macro avg       0.92      0.93      0.92     21661
weighted avg       0.93      0.93      0.93     21661

Accuracy: 92.85351553483218


In [12]:
model_full.save('ann_full.h5')

### Chi Model 

In [13]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(chi_square_x,chi_square_y,test_size=0.30,random_state=10)

In [14]:
model_chi = models.Sequential([
    layers.Dense(2000, input_dim=5, activation='sigmoid'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(2, activation='softmax')
])
model_chi.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_chi.fit(x_train, y_train, epochs=10)

Epoch 1/10
1580/1580 [==============================] - 20s 12ms/step - loss: 0.6272 - accuracy: 0.6187
Epoch 2/10
1580/1580 [==============================] - 22s 14ms/step - loss: 0.5020 - accuracy: 0.6757
Epoch 3/10
1580/1580 [==============================] - 23s 15ms/step - loss: 0.4945 - accuracy: 0.67690s - loss: 0.494
Epoch 4/10
1580/1580 [==============================] - 25s 16ms/step - loss: 0.4892 - accuracy: 0.6775
Epoch 5/10
1580/1580 [==============================] - 25s 16ms/step - loss: 0.4796 - accuracy: 0.6818
Epoch 6/10
1580/1580 [==============================] - 23s 15ms/step - loss: 0.4783 - accuracy: 0.6877
Epoch 7/10
1580/1580 [==============================] - 22s 14ms/step - loss: 0.4749 - accuracy: 0.6862
Epoch 8/10
1580/1580 [==============================] - 22s 14ms/step - loss: 0.4449 - accuracy: 0.6971
Epoch 9/10
1580/1580 [==============================] - 20s 12ms/step - loss: 0.4265 - accuracy: 0.7005
Epoch 10/10
1580/1580 [=========================

In [15]:
y_pred_train = model_chi.predict(x_train)
y_pred_test = model_chi.predict(x_test)

#### Training 

In [16]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[15425 15344]
 [   33 19738]]
              precision    recall  f1-score   support

           0       1.00      0.50      0.67     30769
           1       0.56      1.00      0.72     19771

    accuracy                           0.70     50540
   macro avg       0.78      0.75      0.69     50540
weighted avg       0.83      0.70      0.69     50540

Accuracy: 69.57459438068855


#### Testing 

In [17]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[6609 6641]
 [  10 8401]]
              precision    recall  f1-score   support

           0       1.00      0.50      0.67     13250
           1       0.56      1.00      0.72      8411

    accuracy                           0.69     21661
   macro avg       0.78      0.75      0.69     21661
weighted avg       0.83      0.69      0.69     21661

Accuracy: 69.29504639674991


In [18]:
model_chi.save('ann_chi.h5')

### Feature Selection Model 

In [19]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(feature_selection_x,feature_selection_y,test_size=0.30,random_state=5)

In [20]:
model_feature_selection = models.Sequential([
    layers.Dense(2000, input_dim=5, activation='relu'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(500, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_feature_selection.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_feature_selection.fit(x_train, y_train, epochs=10)

Epoch 1/10
1580/1580 [==============================] - 18s 11ms/step - loss: 0.3860 - accuracy: 0.8225
Epoch 2/10
1580/1580 [==============================] - 17s 11ms/step - loss: 0.2460 - accuracy: 0.8996
Epoch 3/10
1580/1580 [==============================] - 17s 11ms/step - loss: 0.2377 - accuracy: 0.9048
Epoch 4/10
1580/1580 [==============================] - 19s 12ms/step - loss: 0.2221 - accuracy: 0.9098
Epoch 5/10
1580/1580 [==============================] - 18s 11ms/step - loss: 0.2191 - accuracy: 0.9122
Epoch 6/10
1580/1580 [==============================] - 20s 12ms/step - loss: 0.2158 - accuracy: 0.9147
Epoch 7/10
1580/1580 [==============================] - 21s 13ms/step - loss: 0.2052 - accuracy: 0.9203
Epoch 8/10
1580/1580 [==============================] - 21s 13ms/step - loss: 0.2039 - accuracy: 0.9243
Epoch 9/10
1580/1580 [==============================] - 22s 14ms/step - loss: 0.1962 - accuracy: 0.9283
Epoch 10/10
1580/1580 [==============================] - 23s 15m

In [21]:
y_pred_train = model_feature_selection.predict(x_train)
y_pred_test = model_feature_selection.predict(x_test)

#### Training

In [22]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[29678  1232]
 [ 1895 17735]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95     30910
           1       0.94      0.90      0.92     19630

    accuracy                           0.94     50540
   macro avg       0.94      0.93      0.93     50540
weighted avg       0.94      0.94      0.94     50540

Accuracy: 93.81282152750296


#### Testing 

In [23]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[12591   518]
 [  808  7744]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95     13109
           1       0.94      0.91      0.92      8552

    accuracy                           0.94     21661
   macro avg       0.94      0.93      0.94     21661
weighted avg       0.94      0.94      0.94     21661

Accuracy: 93.87839896588338


In [25]:
model_feature_selection.save('ann_feature.h5')

### Slice Model 

In [26]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(slice_x,slice_y,test_size=0.20,random_state=4)

In [27]:
model_slice = models.Sequential([
    layers.Dense(2000, input_dim=4, activation='relu'),
    layers.Dense(500, activation='sigmoid'),
    layers.Dense(50, activation='relu'),
    layers.Dense(2, activation='softmax')
])
model_slice.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=['accuracy'])
model_slice.fit(x_train, y_train, epochs=20)

Epoch 1/20
1805/1805 [==============================] - 19s 10ms/step - loss: 0.4644 - accuracy: 0.7164
Epoch 2/20
1805/1805 [==============================] - 18s 10ms/step - loss: 0.3773 - accuracy: 0.7772
Epoch 3/20
1805/1805 [==============================] - 18s 10ms/step - loss: 0.3584 - accuracy: 0.7971
Epoch 4/20
1805/1805 [==============================] - 18s 10ms/step - loss: 0.3433 - accuracy: 0.8048
Epoch 5/20
1805/1805 [==============================] - 18s 10ms/step - loss: 0.3302 - accuracy: 0.8111
Epoch 6/20
1805/1805 [==============================] - 18s 10ms/step - loss: 0.3184 - accuracy: 0.8223
Epoch 7/20
1805/1805 [==============================] - 18s 10ms/step - loss: 0.3070 - accuracy: 0.8287
Epoch 8/20
1805/1805 [==============================] - 18s 10ms/step - loss: 0.2939 - accuracy: 0.8328
Epoch 9/20
1805/1805 [==============================] - 17s 10ms/step - loss: 0.2818 - accuracy: 0.8431
Epoch 10/20
1805/1805 [==============================] - 18s 10m

In [28]:
y_pred_train = model_slice.predict(x_train)
y_pred_test = model_slice.predict(x_test)

#### Training 

In [29]:
import warnings
warnings.filterwarnings('ignore')
y_pred_train = [np.argmax(element) for element in y_pred_train]
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)


[[28954  6287]
 [ 2379 20140]]
              precision    recall  f1-score   support

           0       0.92      0.82      0.87     35241
           1       0.76      0.89      0.82     22519

    accuracy                           0.85     57760
   macro avg       0.84      0.86      0.85     57760
weighted avg       0.86      0.85      0.85     57760

Accuracy: 84.99653739612188


#### Testing 

In [30]:
warnings.filterwarnings('ignore')
y_pred_test = [np.argmax(element) for element in y_pred_test]
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)

[[7201 1577]
 [ 574 5089]]
              precision    recall  f1-score   support

           0       0.93      0.82      0.87      8778
           1       0.76      0.90      0.83      5663

    accuracy                           0.85     14441
   macro avg       0.84      0.86      0.85     14441
weighted avg       0.86      0.85      0.85     14441

Accuracy: 85.10490963229694


In [31]:
model_slice.save('ann_slice.h5')