In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sn 
import numpy as np 
from keras.models import load_model
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df_full_feature = pd.read_csv('../Dataset/Normalisasi/processed_dataset_slice_norm.csv',sep=',')

In [3]:
ann_full_model = load_model('ann_slice.h5')
ann_full_model

In [4]:
# Dataset Full Feature
full_feature_x = df_full_feature[df_full_feature.columns[:4]]
full_feature_y = df_full_feature['label']

full_feature_x.head(5)

dst       src  Protocol  bytecount
0  0.647059  0.055556       0.0   0.000640
1  0.705882  0.333333       0.5   0.081254
2  0.882353  0.555556       0.0   0.000534
3  0.941176  0.833333       0.5   0.014585
4  0.647059  0.111111       1.0   0.618070

## Training Phase

In [5]:
#Splitting Data 

x_train,x_test,y_train,y_test = train_test_split(full_feature_x,full_feature_y,test_size=0.30,random_state=6)

In [8]:
ann_full_model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1580/1580 [==============================] - 15s 9ms/step - loss: 0.2471 - accuracy: 0.8626
Epoch 2/10
1580/1580 [==============================] - 15s 9ms/step - loss: 0.2419 - accuracy: 0.8660
Epoch 3/10
1580/1580 [==============================] - 15s 9ms/step - loss: 0.2429 - accuracy: 0.8667
Epoch 4/10
1580/1580 [==============================] - 15s 10ms/step - loss: 0.2387 - accuracy: 0.86851s - loss: 0.2388  - E
Epoch 5/10
1580/1580 [==============================] - 19s 12ms/step - loss: 0.2357 - accuracy: 0.8691
Epoch 6/10
1580/1580 [==============================] - 19s 12ms/step - loss: 0.2348 - accuracy: 0.8685
Epoch 7/10
1580/1580 [==============================] - 19s 12ms/step - loss: 0.2314 - accuracy: 0.8690
Epoch 8/10
1580/1580 [==============================] - 18s 12ms/step - loss: 0.2364 - accuracy: 0.8621
Epoch 9/10
1580/1580 [==============================] - 19s 12ms/step - loss: 0.2372 - accuracy: 0.8653
Epoch 10/10
1580/1580 [======================

In [9]:
y_pred_train = ann_full_model.predict(x_train)
y_pred_train

array([[1.0000000e+00, 3.9406616e-09],
       [9.9997497e-01, 2.5016901e-05],
       [1.0000000e+00, 8.4463014e-10],
       ...,
       [6.2134489e-02, 9.3786556e-01],
       [5.4947257e-01, 4.5052734e-01],
       [4.5711792e-01, 5.4288208e-01]], dtype=float32)

In [10]:
def calculate_precision(TP, FP):
    return TP/(TP+FP)


def calculate_fnr(TP, FP, FN):
    return FN/(TP+FP)

### Training Evaluation Result

In [11]:
y_pred_train = [np.argmax(element) for element in y_pred_train]
cm = confusion_matrix(y_train, y_pred_train, labels=[1,0])
TP = cm[0][0]
FP = cm[1][0]
FN = cm[0][1]
TN = cm[1][1]

print(cm)
print(classification_report(y_train, y_pred_train))
print("Accuracy:",accuracy_score(y_train, y_pred_train)*100)
print("Precision",(calculate_precision(TP,FP))*100)
print("False Negative Rate", (calculate_fnr(TP,FP,FN))*100)


[[16812  2845]
 [ 3372 27511]]
              precision    recall  f1-score   support

           0       0.91      0.89      0.90     30883
           1       0.83      0.86      0.84     19657

    accuracy                           0.88     50540
   macro avg       0.87      0.87      0.87     50540
weighted avg       0.88      0.88      0.88     50540

Accuracy: 87.69885239414326
Precision 83.29369797859691
False Negative Rate 14.095323028141102


### Validation Evaluation Result

In [16]:
y_pred_test = ann_full_model.predict(x_test)
y_pred_test

array([[2.4821980e-01, 7.5178021e-01],
       [1.0000000e+00, 2.3931531e-08],
       [0.0000000e+00, 1.0000000e+00],
       ...,
       [1.6554326e-38, 1.0000000e+00],
       [9.9996734e-01, 3.2615993e-05],
       [2.5211072e-01, 7.4788928e-01]], dtype=float32)

In [17]:
y_pred_test = [np.argmax(element) for element in y_pred_test]
cm = confusion_matrix(y_test, y_pred_test, labels=[1,0])
TP = cm[0][0]
FP = cm[1][0]
FN = cm[0][1]
TN = cm[1][1]

print(cm)
print(classification_report(y_test, y_pred_test))
print("Accuracy:",accuracy_score(y_test, y_pred_test)*100)
print("Precision",(calculate_precision(TP,FP))*100)
print("False Negative Rate", (calculate_fnr(TP,FP,FN))*100)


[[ 7294  1231]
 [ 1440 11696]]
              precision    recall  f1-score   support

           0       0.90      0.89      0.90     13136
           1       0.84      0.86      0.85      8525

    accuracy                           0.88     21661
   macro avg       0.87      0.87      0.87     21661
weighted avg       0.88      0.88      0.88     21661

Accuracy: 87.6690826831633
Precision 83.512708953515
False Negative Rate 14.094343943210442


## Testing Phase

In [18]:
test_full_feature = pd.read_csv('../Dataset/Normalisasi/test_processed_dataset_slice_norm.csv',sep=',')

In [19]:
# Dataset Full Feature
full_feature_x = df_full_feature[df_full_feature.columns[:4]]
full_feature_y = df_full_feature['label']

full_feature_x.head(5)

dst       src  Protocol  bytecount
0  0.647059  0.055556       0.0   0.000640
1  0.705882  0.333333       0.5   0.081254
2  0.882353  0.555556       0.0   0.000534
3  0.941176  0.833333       0.5   0.014585
4  0.647059  0.111111       1.0   0.618070

In [20]:
test_pred = ann_full_model.predict(full_feature_x)
test_pred

array([[1.0000000e+00, 2.8555014e-08],
       [4.9333233e-02, 9.5066684e-01],
       [1.0000000e+00, 2.1839659e-09],
       ...,
       [1.0000000e+00, 1.4936516e-08],
       [5.5650502e-01, 4.4349501e-01],
       [9.9476212e-01, 5.2378653e-03]], dtype=float32)

In [21]:
pred_test = [np.argmax(element) for element in test_pred]
cm = confusion_matrix(full_feature_y, pred_test, labels=[1,0])
TP = cm[0][0]
FP = cm[1][0]
FN = cm[0][1]
TN = cm[1][1]

print(cm)
print(classification_report(full_feature_y, pred_test))
print("Accuracy:",accuracy_score(full_feature_y, pred_test)*100)
print("Precision",(calculate_precision(TP,FP))*100)
print("False Negative Rate", (calculate_fnr(TP,FP,FN))*100)

[[24106  4076]
 [ 4812 39207]]
              precision    recall  f1-score   support

           0       0.91      0.89      0.90     44019
           1       0.83      0.86      0.84     28182

    accuracy                           0.88     72201
   macro avg       0.87      0.87      0.87     72201
weighted avg       0.88      0.88      0.88     72201

Accuracy: 87.68992119222725
Precision 83.35984507918943
False Negative Rate 14.095027318625078
